from copy import deepcopy
import random
import math
import pickle
import numpy as np
from entropy_tpp import TE_estimation_tpp, run_multiple_estimation
from entropy_tpp import save_dict_indented
import torch
import time
import matplotlib.pyplot as plt

# the true value of the TE is 0.5076 ± 0.001 nats per second
# Returens spike trains for source (y) and target (x) processes
def generate_spike_trains_CoTETE(RATE_Y = 1.0, RATE_X_MAX=10, NUM_Y_EVENTS=3e6, seed=0):
    """
    Generates spike trains y (source) and x (target).
    
    Also returns diagnostic data to analyze the effective rate:
    - all_delta_t_candidates: All delta_t values generated by the "parent" (RATE_X_MAX) process.
    - all_accepted_delta_t: Only the delta_t values that were "kept" (thinned) to form event_train_x.
    """
    random.seed(seed)
    np.random.seed(seed)
    
    event_train_y = []
    event_train_x = []
    
    # --- Diagnostic lists ---
    all_delta_t_candidates = []
    all_accepted_delta_t = []

    # event_train_x.append(0)

    # --- Generate y process (homogeneous Poisson) ---
    # This is a fast and correct way to generate a Poisson process
    inter_arrivals = np.random.exponential(scale=1.0 / RATE_Y, size=int(NUM_Y_EVENTS))
    event_train_y = np.cumsum(inter_arrivals).tolist()
    
    if not event_train_y:
        print("Warning: No events generated for process y.")
        return [], [], [], []

    most_recent_y_index = 0
    previous_x_candidate = 0
    
    # --- Generate x process (inhomogeneous thinning) ---
    while most_recent_y_index < (len(event_train_y) - 1):

        # 1. Generate candidate from the parent (RATE_X_MAX) process
        this_x_candidate = previous_x_candidate + random.expovariate(RATE_X_MAX)

        # 2. Find the most recent 'y' spike
        while most_recent_y_index < (len(event_train_y) - 1) and this_x_candidate > event_train_y[most_recent_y_index + 1]:
            most_recent_y_index += 1

        # 3. Calculate delta_t
        delta_t = this_x_candidate - event_train_y[most_recent_y_index]
        # --- Store diagnostic data ---
        all_delta_t_candidates.append(delta_t)

        # 4. Calculate the true instantaneous rate (the hazard function)
        rate = 0
        if delta_t > 1:
            rate = 0.5
        else:
            # This is the hazard function lambda(delta_t)
            rate = 0.5 + 5.0 * math.exp(-50 * (delta_t - 0.5)**2) - 5.0 * math.exp(-50 * (0.5)**2)
        
        # this_x_candidate += delta_t
        # 5. Thinning (Accept/Reject)
        if random.random() < rate / float(RATE_X_MAX):
            # assert delta_t >= 0, "delta_t should be non-negative, but got {}".format(delta_t)
            event_train_x.append(this_x_candidate)
            # --- Store diagnostic data on acceptance ---
            all_accepted_delta_t.append(delta_t)

        previous_x_candidate = this_x_candidate

    # neg_delta_ts = [(dt, i) for i, dt in enumerate(all_accepted_delta_t) if dt < 0]
    # if neg_delta_ts:
    #     print(f"Warning: Found {len(neg_delta_ts)} accepted negative delta_t values: {neg_delta_ts[:5]}...")
    
    # neg_delta_ts_all = [(dt, i) for i, dt in enumerate(all_delta_t_candidates) if dt < 0]
    # if neg_delta_ts_all:
    #     print(f"Warning: Found {len(neg_delta_ts_all)} candidate negative delta_t values: {neg_delta_ts_all[:5]}...")
    # The problem will persist for all iterations until the this_x_candidate
    # time becomes larger than the first Y event time (event_train_y[0]).
    
    return event_train_y, event_train_x, all_delta_t_candidates, all_accepted_delta_t

def plot_average_firing_rate(all_delta_t_candidates, all_accepted_delta_t, RATE_X_MAX):
    """
    Plots the empirical average firing rate based on the simulation data
    and compares it to the theoretical hazard function.
    """

    print("Plotting results...")

    # --- 1. Calculate the empirical rate from data ---
    # We will histogram the data up to delta_t = 1.5
    bins = np.linspace(0, 1.5, 101)

    # Get counts for all "candidate" spikes
    counts_candidates, bin_edges = np.histogram(all_delta_t_candidates, bins=bins)

    # Get counts for only "accepted" spikes
    print("Plotting results...")
    
    # --- 1. Calculate the empirical rate from data ---
    # We will histogram the data up to delta_t = 1.5
    bins = np.linspace(0, 1.5, 101)
    
    # Get counts for all "candidate" spikes
    counts_candidates, bin_edges = np.histogram(all_delta_t_candidates, bins=bins)
    
    # Get counts for only "accepted" spikes
    counts_accepted, _ = np.histogram(all_accepted_delta_t, bins=bins)
    
    plt.figure(figsize=(10, 4))
    plt.hist(all_delta_t_candidates, bins=100, alpha=0.6, label='All Candidates', density=True)
    plt.hist(all_accepted_delta_t, bins=100, alpha=0.6, label='Accepted Candidates', density=True)
    plt.xlabel('Δt')
    plt.ylabel('Density')
    plt.title('Histogram of Δt Candidates vs Accepted')
    plt.legend()
    plt.tight_layout()
    plt.savefig("./results/delta_t_histograms.png")
    plt.close()

    # The empirical rate is (accepted / candidates) * RATE_X_MAX
    # This is the inverse of the thinning algorithm's probability
    empirical_rate = RATE_X_MAX * np.divide(
        counts_accepted, 
        counts_candidates, 
        out=np.zeros_like(counts_accepted, dtype=float), 
        where=counts_candidates != 0
    )
    
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
    
    # --- 2. Define the theoretical rate (the hazard function) ---
    def theoretical_hazard_function(t):
        if t > 1:
            return 0.5
        else:
            return 0.5 + 5.0 * math.exp(-50 * (t - 0.5)**2) - 5.0 * math.exp(-50 * (0.5)**2)

    # Vectorize the function for plotting
    v_hazard = np.vectorize(theoretical_hazard_function)
    t_values = np.linspace(0, 1.5, 200)
    theoretical_rate = v_hazard(t_values)

    # --- 3. Create the plot ---
    plt.figure(figsize=(10, 6))
    
    # Plot the empirical rate
    plt.plot(bin_centers, empirical_rate, 'b-', label='Empirical Rate', linewidth=2)
    
    # Plot the theoretical rate
    plt.plot(t_values, theoretical_rate, 'r--', label='Theoretical Rate', linewidth=2)
    
    plt.title('Average Firing Rate of Target vs. Time Since Last Source Spike ($\Delta t$)')
    plt.xlabel('Time Since Last Source Spike')
    plt.ylabel('Firing Rate (Hz)')
    plt.legend()
    plt.grid(True)
    # plt.ylim(0, RATE_X_MAX / 1.5) # Set Y-limit to see the shape clearly
    plt.savefig("./results/avg_firing_rate_from_last_source.png")
    print("Plot saved as avg_firing_rate_from_last_source.png")

def plot_firing_rate_over_time(event_train_x, time_step=500.0):
    """
    Plots the firing rate of the target process over absolute simulation time.
    """
    
    print(f"Plotting results for firing_rate_over_time.png with time_step={time_step}s...")
    
    if len(event_train_x) < 2:
        print("Not enough target events to plot firing rate over time.")
        return

    # 1. Get total duration
    total_duration = event_train_x[-1]
    
    # 2. Create time bins
    # We want about 1000 bins for a good overview
    num_bins = max(100, int(total_duration / time_step))
    bins = np.linspace(0, total_duration, num_bins)
    actual_time_step = bins[1] - bins[0] # Get the precise time step
    
    # 3. Count spikes in each bin
    counts, bin_edges = np.histogram(event_train_x, bins=bins)
    
    # 4. Calculate rate (spikes per second)
    firing_rate = counts / actual_time_step
    
    # 5. Get bin centers for plotting
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
    
    # 6. Calculate the overall average rate
    average_rate = len(event_train_x) / total_duration
    
    # 7. Create the plot
    plt.figure(figsize=(12, 6))
    
    # Plot the binned firing rate
    plt.plot(bin_centers, firing_rate, 'b-', label=f'Binned Firing Rate (step={actual_time_step:.2f}s)')
    
    # Plot a line for the average rate
    plt.axhline(average_rate, color='r', linestyle='--', label=f'Overall Average Rate: {average_rate:.2f} Hz')
    
    plt.title('Firing Rate of Target Process Over Simulation Time')
    plt.xlabel('Absolute Time (s)')
    plt.ylabel('Firing Rate (Hz)')
    plt.legend()
    plt.grid(True)
    plt.xlim(0, total_duration)
    plt.ylim(0) # Rate can't be negative
    
    plt.savefig("./results/firing_rate_over_time.png")
    print("Plot saved as firing_rate_over_time.png")


if __name__ == "__main__":
    # Define simulation parameters
    seed=52
    num_source_events = int(2e+4)
    source_events, target_events, candidates, accepted = generate_spike_trains_CoTETE(RATE_Y = 1.0, RATE_X_MAX=6, NUM_Y_EVENTS=num_source_events,seed=seed)
    # print("x_events:", x_events[:5], "...", x_events[-5:])
    # print("y_events:", y_events[:5], "...", y_events[-5:])
    plot_average_firing_rate(candidates, accepted, RATE_X_MAX=6)
    plot_firing_rate_over_time(target_events, time_step=10.0)
    SIMULATION_TIME = min(source_events[-1], target_events[-1])  # seconds
    # Print summary statistics
    print("\n--- Simulation Results ---")
    print(f"Total events for Process X: {len(source_events)}")
    print(f"Total events for Process Y: {len(target_events)}")
    print(f"Simulation Time: {SIMULATION_TIME} seconds")

    torch.manual_seed(seed)
    np.random.seed(seed)
    time_series_length = SIMULATION_TIME   # in seconds, Length of the time series
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f'Using device: {device}')

    configs = {
            "model_config_yy": {
            "model_name": "LogNormMix_yy",
            "context_size": 16,
            "num_mix_components": 8,
            "hidden_sizes": [4, 16],
            "context_extractor": "lstm",
            "activation_func": "GELU"
        },
        "model_config_yyx": {
            "model_name": "LogNormMix_yyx",
            "context_size": 8,
            "num_mix_components": 32,
            "hidden_sizes": [8, 32],
            "context_extractor": "gru",
            "activation_func": "Tanh"
        },
        "train_config_yy": {
            "L2_weight": 3.8379954060256066e-08,
            "L_entropy_weight": 0.00022756667123420592,
            "L_sep_weight": 2.891600870711327e-10,
            "L_scale_weight": 1.8621741962089573e-05,
            "learning_rate": 0.0024284476869901616,
            "max_epochs": 500,
            "display_step": 5,
            "patience": 20
        },
        "train_config_yyx": {
            "L2_weight": 0.00015034955189675413,
            "L_entropy_weight": 0.0002915120808357504,
            "L_sep_weight": 6.238313212626435e-06,
            "L_scale_weight": 4.033731713458755e-08,
            "learning_rate": 0.007882822631563417,
            "max_epochs": 500,
            "display_step": 5,
            "patience": 20
        },
        "data_prep_config":{
            "batch_size": 128,          # Number of sequences in a batch
            "shuffle": False,                 # Whether to shuffle the time series before splitting into train/val/test
            "total_time": time_series_length,              # in second, Total time of the sequences
            "verbose": False
        },
        "device": device,
        "verbose": False,  # Whether to print the training statistics
        "plot_histograms": False,  # Whether to plot the conditional histograms
        "plot_pp": False,            # Whether to plot the probability - probability plots
        "history_length": 256,             # in number of bins, Length of the history to use for the model
    }

    # Save the config for reference
    save_dict_indented(configs, f"./results/config_{seed}.txt")
    
    config_plot = deepcopy(configs)
    config_plot["plot_pp"] = True
    start_time = time.time()
    (TE_test, H_yy_test, H_yyx_test), (log_loss_yy, log_loss_yyx) = TE_estimation_tpp(
            event_time=[torch.tensor(target_events,dtype=torch.float), torch.tensor(source_events,dtype=torch.float)], 
            configs=config_plot, 
            seed=seed
    )
    end_time = time.time()
    duration = end_time - start_time
    print(f"\n--- TE Estimation Completed in {duration/60:.2f} minutes ---")
    print(f"Estimated Transfer Entropy (nats per second): {TE_test}")
    print(f"Estimated h_hazard(Y_t+1|Y_t) (nats per second): {H_yy_test}")
    print(f"Estimated h_hazard(Y_t+1|Y_t,X_t) (nats per second): {H_yyx_test}")
    print(f"Log Loss pdf (Y_t+1|Y_t): {log_loss_yy}")
    print(f"Log Loss pdf (Y_t+1|Y_t,X_t): {log_loss_yyx}")

    run_multiple_estimation(
        target_events=torch.tensor(target_events, dtype=torch.float),
        source_events=torch.tensor(source_events, dtype=torch.float),
        configs=configs,
        n_runs=10,
        seed=seed
    )