import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

def prepare_data(file_path):
    """Loads and prepares the dataframe with descriptive labels."""
    df = pd.read_csv(file_path)
    # Using the column names generated by calculate_te.py
    df['source_label'] = df['source_group_id'] + " " + df['source_neuron_id'].astype(str)
    df['target_label'] = df['target_group_id'] + " " + df['target_neuron_id'].astype(str)
    return df

def draw_combined_te_heatmap(df, output_filename, title, value_col='te_mean'):
    """
    Generates a figure with two side-by-side heatmaps (BC->POm and POm->BC)
    sharing a single color bar.
    """
    # Filter directions
    bc_to_pom = df[(df['source_group_id'] == 'BC') & (df['target_group_id'] == 'POm')]
    pom_to_bc = df[(df['source_group_id'] == 'POm') & (df['target_group_id'] == 'BC')]

    # Pivot data - using te_mean by default
    pivot_bc_pom = bc_to_pom.pivot(index='target_label', columns='source_label', values=value_col)
    pivot_pom_bc = pom_to_bc.pivot(index='target_label', columns='source_label', values=value_col)

    # Sort labels for consistent ordering
    pivot_bc_pom = pivot_bc_pom.sort_index(axis=0).sort_index(axis=1)
    pivot_pom_bc = pivot_pom_bc.sort_index(axis=0).sort_index(axis=1)

    # Determine global scale for shared colorbar
    vmin = df[value_col].min()
    vmax = df[value_col].max()

    # Create figure
    fig, axes = plt.subplots(1, 2, figsize=(18, 8))
    
    # Plot BC -> POm
    sns.heatmap(
        pivot_bc_pom, ax=axes[0], annot=True, fmt=".1f", 
        cmap="YlGnBu", vmin=vmin, vmax=vmax, cbar=False
    )
    axes[0].set_title("BC to POm")
    axes[0].set_xlabel("Source (BC)")
    axes[0].set_ylabel("Target (POm)")

    # Plot POm -> BC
    sns.heatmap(
        pivot_pom_bc, ax=axes[1], annot=True, fmt=".1f", 
        cmap="YlGnBu", vmin=vmin, vmax=vmax, cbar=False
    )
    axes[1].set_title("POm to BC")
    axes[1].set_xlabel("Source (POm)")
    axes[1].set_ylabel("Target (BC)")

    # Add shared colorbar
    mappable = axes[0].collections[0]
    cbar_ax = fig.add_axes([0.92, 0.15, 0.02, 0.7]) 
    fig.colorbar(mappable, cax=cbar_ax, label='TE Mean')

    plt.suptitle(title, fontsize=16)
    plt.subplots_adjust(right=0.9, wspace=0.3)
    
    plt.savefig(output_filename, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved: {output_filename}")

def draw_combined_te_heatmap_significant(df, output_filename, title):
    """
    Filters out results where the confidence interval includes zero.
    Sets te_mean to 0 if te_ci_lower <= 0.
    """
    df_sig = df.copy()
    
    # Logic: If te_ci_lower <= 0, the result is not statistically significant.
    # We set these means to 0 to mask them in the heatmap.
    df_sig.loc[df_sig['te_ci_lower'] <= 0, 'te_mean'] = 0
    
    full_title = f"{title} (Significant Results Only: ci_lower > 0)"
    draw_combined_te_heatmap(df_sig, output_filename, full_title)

def draw_combined_te_heatmap_significant_larger(df, output_filename, title, threshold=0.1):
    """
    Filters out results where the confidence interval includes zero.
    Sets te_mean to 0 if te_ci_lower <= threshold.
    """
    df_sig = df.copy()
    
    # Logic: If te_ci_lower <= threshold, the result is not statistically significant.
    # We set these means to 0 to mask them in the heatmap.
    df_sig.loc[df_sig['te_ci_lower'] <= threshold, 'te_mean'] = 0
    
    full_title = f"{title} (Significant Results Only: ci_lower > {threshold})"
    draw_combined_te_heatmap(df_sig, output_filename, full_title)


if __name__ == "__main__":
    DATA_PATH = "results/te_results_hpc.csv"
    
    try:
        data = prepare_data(DATA_PATH)
        
        # 1. Standard heatmap (shows all means, including negative/non-significant)
        draw_combined_te_heatmap(
            data, 
            "results/te_heatmap_standard.png", 
            "Transfer Entropy (All Results)"
        )
        
        # 2. Significant-only heatmap (filters by ci_lower)
        draw_combined_te_heatmap_significant(
            data, 
            "results/te_heatmap_95ci.png", 
            "Transfer Entropy"
        )
        
        # 3. Significant-only heatmap (filters by 0.1 95%ci_lower)
        draw_combined_te_heatmap_significant_larger(
            data, 
            "results/te_heatmap_95ci_g0.1.png", 
            "Transfer Entropy",
            0.1
        )

        draw_combined_te_heatmap_significant_larger(
            data, 
            "results/te_heatmap_95ci_g0.075.png", 
            "Transfer Entropy",
            0.075
        )
    except FileNotFoundError:
        print(f"Error: {DATA_PATH} not found.")
    except KeyError as e:
        print(f"Error: Missing expected column in CSV: {e}")